# Generated by Django 6.0.3 on 2026-04-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='candidate_response',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='role',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
