# Generated by Django 6.0.3 on 2026-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_candidate_response_applicant_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='candidate_response',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='role',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
