# Generated by Django 6.0.3 on 2026-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_candidate_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='candidate_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
